[project]
name = "novel-rag"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "llama-index>=0.14.12",
    "uvicorn>=0.40.0",
]
